client_secret: JgARl5rWKs4k8TTuG1OgFcaxrxsjmpHl
debug: false
disable_auto_update: true
disable_command_execute: false
disable_force_update: true
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
report_delay: 4
server: nzag.faiz.us.kg:8008
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: false
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: a0066281-5b04-4e4a-aa1d-010c3925d1fc
